<?php

/**
 * @file
 * Contains user_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function user_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_api module.
    case 'help.page.user_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function user_api_install()
{
    // 为已认证用户添加权限
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, [
        'restful get user_api_user_info'
    ]);
}

/**
 * Implements hook_theme().
 */
function user_api_theme() {
  return [
    'user_api' => [
      'render element' => 'children',
    ],
  ];
}
